# Netlify build configuration
[build]
  base = ""
  command = "echo Building Functions"
  publish = "frontend/build"
  functions = "netlify/functions"

[functions]
  external_node_modules = ["express", "pg-hstore", "bcrypt", "@supabase/supabase-js", "passport", "jsonwebtoken"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
